<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Majorsoft.Blazor.Components.Debounce" Version="1.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend.Core\Backend.Core.csproj" />
  </ItemGroup>
	
	<ItemGroup>
		<Content Update="wwwroot\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="wwwroot\css\" />
	</ItemGroup>
</Project>
